[[protocols]]
name = "z69p remote"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0x101 = "KEY_POWER"
0x105 = "KEY_LEFT"
0x106 = "KEY_RIGHT"
0x103 = "KEY_UP"
0x108 = "KEY_DOWN"
0x107 = "KEY_OK"
0x125 = "KEY_EXIT"
0x102 = "KEY_MUTE"
0x128 = "KEY_VOLUMEUP"
0x129 = "KEY_VOLUMEDOWN"
0x127 = "KEY_HOME"
0x126 = "KEY_CONTEXT_MENU"
0x13  = "KEY_INFO"
